### ISSUE TITLE
Find a suitable name for the repo

### ISSUE THREAD

**Issue by vlopes11** [FuelLabs/fuel-pbft#2]
The implementation won't reflect the strict form of pbft but instead will be based in tendermint.

We have some differences such as the block being proposed after precommit instead of commit and the round being declared as a tuple `(height, round)` instead of an abstract descriptor.

Having `fuel-pbft` is misleading because it suggests this is a general model for pbft, when in fact this is one concrete instance of pbft.

As suggestion: `fuel-polka`

**Comment by adlerjohn** [comment]
While polkas are a thing in Tendermint, I would avoid it due to the similarity to Polkadot. My preference would be `fuel-tendermint`.

**Comment by Voxelot** [comment]
We could also go even more generic and just call it `fuel-bft` since it may not be an exact implementation of tendermint (types might be a little different etc).

**Comment by adlerjohn** [comment]
Due to voting apathy, `fuel-bft` wins.
